### PR TITLE
docs(deps): libraries-bom 24.4.0 release in google-http-java-client

### PR DESCRIPTION
**Pull request by suztomo**
@Neenu1995 @mpeddada1

### CODE REVIEW

**Comment by mpeddada1** [comment]
Looks like we have a small formatting issue:

```
To fix formatting errors, run "mvn com.coveo:fmt-maven-plugin:format"
Error:  Non complying file: /home/runner/work/google-http-java-client/google-http-java-client/google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
```
Is it related to the upgrade?

**Comment by mpeddada1** [comment]
Got it, thanks!

**Comment by suztomo** [comment]
I see "ci / lint (pull_request)" is a required check and blocking merge.

**Comment by suztomo** [comment]
The repository setting updated until the permanent fix comes.

**Pull request merged**
