### PR TITLE
chore: fix lint

### PR DESCRIPTION
**Pull request by Capstan**
This fixes the one error in the non-blocking linter CI results.

### CODE REVIEW

**Comment by suztomo** [comment]
There was some mixed tooling (OwlBot) that prevented us from using the latest google-java-format.

https://github.com/googleapis/google-http-java-client/pull/1508

**Comment by suztomo** [comment]
Trying "owlbot:run" label.

**Comment by suztomo** [comment]
OwlBot reverted the format change because it uses an old version of google-java-format:

Screen Shot 2022-08-31 at 10 38 57 PM

**Comment by Capstan** [comment]
Boo. I suppose I should just drop this then.

**Pull request closed without merging**
